# Generated by Django 3.1.1 on 2021-01-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='last_bid',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
