# Generated by Django 3.1.1 on 2020-11-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='start_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
