# Generated by Django 3.1.1 on 2020-12-20 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201209_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='faves', to=settings.AUTH_USER_MODEL),
        ),
    ]
