# Generated by Django 3.1.1 on 2021-01-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210103_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created',
        ),
    ]
