# Generated by Django 3.1.1 on 2020-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201129_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, max_digits=225),
        ),
    ]
