# Generated by Django 3.1.1 on 2021-01-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210105_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Food', 'Food'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Other', 'Other')], default='Other', max_length=225),
        ),
    ]
