# Generated by Django 3.1.1 on 2020-11-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201129_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='descrip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
