# Generated by Django 3.1.1 on 2020-12-26 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201220_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='start_bid',
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=225),
        ),
        migrations.AlterField(
            model_name='listing',
            name='favourited',
            field=models.ManyToManyField(blank=True, default=None, related_name='faves', to=settings.AUTH_USER_MODEL),
        ),
    ]
