# Generated by Django 3.1.1 on 2020-12-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201226_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='auction',
            new_name='listing',
        ),
    ]
