# Generated by Django 3.1.1 on 2020-12-28 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_start_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid_amount',
        ),
        migrations.AddField(
            model_name='bids',
            name='date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
