# Generated by Django 3.1.1 on 2021-01-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='approved_comment',
        ),
    ]
